### ISSUE TITLE
npm run give me this output 

### ISSUE THREAD

**Issue by Xanaxus** [ethans333/soundcloudTerminal#3]
```
➜  npm run
Lifecycle scripts included in soundcloudterminal@1.0.0:
  start
    node src/main.js
```

**Comment by ethans333** [comment]
Just type in _node main_ when you're in the src folder

**Comment by Xanaxus** [comment]
Hey I did That and i was able to run it but i am getting the following error when doing a search by artist and by song name
```
KatyPerry?
 Yes
 No 
/home/ivan/Downloads/soundcloudTerminal/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null
    at __puppeteer_evaluation_script__:3:57
    at ExecutionContext._evaluateInternal (/home/ivan/Downloads/soundcloudTerminal/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/ivan/Downloads/soundcloudTerminal/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async Object.loadArtist (/home/ivan/Downloads/soundcloudTerminal/src/loadArtist.js:101:29)
```
